version: '3.4'

services:
  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    dns:
      - 8.8.8.8
      - 4.4.4.4
    network_mode: host